<?php

use Illuminate\Database\Seeder;

class BooksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
//        $books = factory(Book::class)->times(50)->make();
//        Book::insert($books->toArray());
        \DB::table('books')->delete();
        
        \DB::table('books')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => '银河帝国Ⅰ基地',
                'isbn' => '978-7-5399-4979-6',
                'author' => '〔美〕艾萨克・阿西莫夫著 叶李华译',
                'publisher' => '江苏文艺出版社',
                'pub_date' => '2015-01-01',
                'price' => '29.90',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '9.2',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => '银河帝国Ⅱ基地与帝国',
                'isbn' => '978-7-5399-4978-9',
                'author' => '〔美〕艾萨克・阿西莫夫著 叶李华译',
                'publisher' => '江苏文艺出版社',
                'pub_date' => '2015-01-01',
                'price' => '29.90',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '9.4',
                'note' => ' 社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => '银河帝国Ⅲ第二帝国',
                'isbn' => '978-7-5399-5268-0',
                'author' => '〔美〕艾萨克・阿西莫夫著 叶李华译',
                'publisher' => '江苏文艺出版社',
                'pub_date' => '2015-01-01',
                'price' => '29.90',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '9.6',
                'note' => ' 社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => '银河帝国Ⅳ基地前奏',
                'isbn' => '978-7-5399-5434-9',
                'author' => '〔美〕艾萨克・阿西莫夫著 叶李华译',
                'publisher' => '江苏文艺出版社',
                'pub_date' => '2015-01-01',
                'price' => '39.90',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '9.4',
                'note' => ' 社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => '银河帝国Ⅴ迈向基地',
                'isbn' => '978-7-5399-5435-6',
                'author' => '〔美〕艾萨克・阿西莫夫著 叶李华译',
                'publisher' => '江苏文艺出版社',
                'pub_date' => '2015-01-01',
                'price' => '39.90',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '9.6',
                'note' => ' 社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => '银河帝国Ⅵ基地边缘',
                'isbn' => '978-7-5399-5436-3',
                'author' => '〔美〕艾萨克・阿西莫夫著 叶李华译',
                'publisher' => '江苏文艺出版社',
                'pub_date' => '2015-01-01',
                'price' => '39.90',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '9.6',
                'note' => ' 社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => '银河帝国Ⅶ基地与地球',
                'isbn' => '978-7-5399-5437-0',
                'author' => '〔美〕艾萨克・阿西莫夫著 叶李华译',
                'publisher' => '江苏文艺出版社',
                'pub_date' => '2015-01-01',
                'price' => '46.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '9.2',
                'note' => ' 社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => '伤心者',
                'isbn' => '978-7-5399-8643-2',
                'author' => '何夕.著',
                'publisher' => '江苏凤凰文艺出版社',
                'pub_date' => '2015-10-01',
                'price' => '35.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '9.0',
                'note' => ' 社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => '六道众生',
                'isbn' => '978-7-5354-5865-0',
                'author' => '何夕.著',
                'publisher' => '长江文艺出版社',
                'pub_date' => '2012-09-01',
                'price' => '32.00',
                'total' => 3,
                'remain_num' => 3,
                'douban_score' => '0.0',
                'note' => ' 社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => '湿婆之舞',
                'isbn' => '978-7-5364-7481-9',
                'author' => '江波.著',
                'publisher' => '四川出版集团・四川科学技术出版社',
                'pub_date' => '2012-10-01',
                'price' => '38.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '有作者亲笔签名（林绍鹏捐赠）',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => '银河之心・暗黑深渊',
                'isbn' => '978-7-5364-09-4',
                'author' => '江波.著',
                'publisher' => '四川出版集团・四川科学技术出版社',
                'pub_date' => '2013-08-01',
                'price' => '34.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '有作者亲笔签名（林绍鹏捐赠）',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => '差分机',
                'isbn' => '978-7-5133-1181-6',
                'author' => '威廉・吉布森 布鲁斯・斯特林.著 雒城.译',
                'publisher' => '新星出版社',
                'pub_date' => '2014-11-01',
                'price' => '45.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '杨一苇捐赠',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => '与机器人同行',
                'isbn' => '987-7-5364-8215-9',
                'author' => '阿缺.著',
                'publisher' => '四川出版集团・四川科学技术出版社',
                'pub_date' => '2015-10-01',
                'price' => '32.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => '湮灭 遗落的南境',
                'isbn' => '978-7-5455-1616-6',
                'author' => '〔美〕杰夫・范德米尔.著 胡绍晏.译',
                'publisher' => '天地出版社',
                'pub_date' => '2016-02-01',
                'price' => '28.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.8',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => '医院',
                'isbn' => '978-7321-6044-0',
                'author' => '韩松.著',
                'publisher' => '上海文艺出版社',
                'pub_date' => '2016-05-01',
                'price' => '35.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '有作者亲笔签名（杨昊霖捐赠）',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => '三体X观想之宙',
                'isbn' => '978-7-229-03981-3',
                'author' => '宝树著',
                'publisher' => '重庆出版社',
                'pub_date' => '2011-06-01',
                'price' => '17.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '有作者亲笔签名',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => '时间之墟',
                'isbn' => '978-7-5354-6887-1',
                'author' => '宝树著',
                'publisher' => '长江文艺出版社',
                'pub_date' => NULL,
                'price' => '29.80',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '8.0',
                'note' => ' 社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => '与吾同在',
                'isbn' => '978-7-229-04528-9',
                'author' => '王晋康著',
                'publisher' => '重庆出版社',
                'pub_date' => '2011-09-01',
                'price' => '29.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '有作者亲笔签名（林绍鹏捐赠）',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => '2037化学笔记',
                'isbn' => ' 978-7-5354-6161-2',
                'author' => '陈奕璐.著',
                'publisher' => '长江文艺出版社',
                'pub_date' => NULL,
                'price' => '26.80',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => '星云Ⅳ',
                'isbn' => '7-5364-6050-3',
                'author' => '陈楸帆 飞氘 七月',
                'publisher' => '四川出版集团・四川科学技术出版社',
                'pub_date' => '2006-09-01',
                'price' => '15.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '8.2',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => '星云Ⅴ',
                'isbn' => '7-5364-6099-6',
                'author' => '吴弼川.著',
                'publisher' => '四川出版集团・四川科学技术出版社',
                'pub_date' => '2006-11-01',
                'price' => '15.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '8.2',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => '本日优惠日',
                'isbn' => '978-7-5329-4208-4',
                'author' => '朱川凑人.著  丁丁虫.译',
                'publisher' => '山东文艺出版社',
                'pub_date' => '2013-08-01',
                'price' => '25.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '杨一苇捐赠',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => '银河系搭车客指南',
                'isbn' => ' 978-7-5327-5468-7',
                'author' => '〔英〕道格拉斯・亚当斯.著  姚向辉.译',
                'publisher' => '上海译文出版社',
                'pub_date' => '2014-11-01',
                'price' => '26.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '8.6',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => '基本上无害',
                'isbn' => '978-7-5364-6603-6',
                'author' => '〔英〕道格拉斯・亚当斯.著 胡纾译',
                'publisher' => '四川出版集团・四川科学技术出版社',
                'pub_date' => '2008-12-01',
                'price' => '20.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '8.4',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => '拜拜，多谢你们的鱼',
                'isbn' => '978-7-5364-6602-9',
                'author' => '〔英〕道格拉斯・亚当斯.著 胡纾译',
                'publisher' => '四川出版集团・四川科学技术出版社',
                'pub_date' => '2008-12-01',
                'price' => '16.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => '生命丶宇宙的一切',
                'isbn' => '978-7-5364-6597-8',
                'author' => '〔英〕道格拉斯・亚当斯.著 胡纾译',
                'publisher' => '四川出版集团・四川科学技术出版社',
                'pub_date' => '2008-12-01',
                'price' => '18.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.2',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => '科幻原力觉醒',
                'isbn' => '978-7-5306-6937-2',
                'author' => '郑军/主编',
                'publisher' => '百花文艺出版社',
                'pub_date' => NULL,
                'price' => '20.00',
                'total' => 2,
                'remain_num' => 2,
                'douban_score' => '0.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => '蚁人・ 重生之人',
                'isbn' => '978-7-302-43144-2',
                'author' => '〔美〕尼克・斯宾塞/著〔西班牙〕拉蒙・罗赞拉斯 等/绘  克瑞斯/译',
                'publisher' => '清华大学出版社',
                'pub_date' => NULL,
                'price' => '45.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => '蚁人・ 电影前奏',
                'isbn' => '978-7-302-42039-2',
                'author' => '威尔・科罗纳・皮尔格林/著〔墨〕米格尔・赛普尔韦达 等/绘  克瑞斯/译',
                'publisher' => '清华大学出版社',
                'pub_date' => NULL,
                'price' => '55.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '王晋康  郝景芳',
                'publisher' => '成都市邮政局',
                'pub_date' => '2008-08-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2008-02-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2008-05-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2009-01-01',
                'price' => '5.00',
                'total' => 2,
                'remain_num' => 2,
                'douban_score' => '0.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2009-03-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2009-06-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2009-08-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.4',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2009-10-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.2',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2010-03-01',
                'price' => '5.00',
                'total' => 2,
                'remain_num' => 2,
                'douban_score' => '7.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2010-04-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2010-08-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.2',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2010-09-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '6.6',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2011-09-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.2',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2011-10-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '0.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2012-02-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2012-05-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.2',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2012-09-01',
                'price' => '5.00',
                'total' => 2,
                'remain_num' => 2,
                'douban_score' => '7.2',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2013-01-01',
                'price' => '5.00',
                'total' => 2,
                'remain_num' => 2,
                'douban_score' => '7.6',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2013-12-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2014-03-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.4',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2014-04-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.6',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2014-05-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.6',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2014-06-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.2',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2014-07-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.4',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2014-08-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.4',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
            'name' => '科幻世界(译文版)',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2014-09-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.6',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2014-09-01',
                'price' => '5.00',
                'total' => 2,
                'remain_num' => 2,
                'douban_score' => '7.6',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2014-10-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.6',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2014-11-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.0',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2014-12-01',
                'price' => '5.00',
                'total' => 2,
                'remain_num' => 2,
                'douban_score' => '7.2',
                'note' => '社团财产',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2015-01-01',
                'price' => '5.00',
                'total' => 2,
                'remain_num' => 2,
                'douban_score' => '6.8',
                'note' => '杨一苇捐赠',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2015-02-01',
                'price' => '5.00',
                'total' => 2,
                'remain_num' => 2,
                'douban_score' => '7.8',
                'note' => '杨一苇捐赠',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2015-03-01',
                'price' => '5.00',
                'total' => 2,
                'remain_num' => 2,
                'douban_score' => '7.4',
                'note' => '杨一苇捐赠',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2015-04-01',
                'price' => '5.00',
                'total' => 2,
                'remain_num' => 2,
                'douban_score' => '7.2',
                'note' => '杨一苇捐赠',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'name' => '科幻世界',
                'isbn' => '1003-7055',
                'author' => '',
                'publisher' => '成都市邮政局',
                'pub_date' => '2015-05-01',
                'price' => '5.00',
                'total' => 1,
                'remain_num' => 1,
                'douban_score' => '7.6',
                'note' => '杨一苇捐赠',
                'description' => NULL,
                'recommend' => 0,
                'cid' => 0,
                'tags' => NULL,
                'book_pic' => NULL,
                'user_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}